server:
  port: 18084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "[%d{MM-dd-yyyy HH:mm:ss,SSS zZ}] [%t] [category=&quot;%.50c{3}&quot;; prio=&quot;%-4p&quot; CorrelationId=&quot;%X{CorrelationId}&quot;;] [UserId=&quot;%X{UserId}&quot;; ] msg=%m%n"
