server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  ignored-services: "*"


# The following is moved into bootstrap.yml of Zuul server
#zuul:
#  routes:
#    auth:
#      path: /uaa/**
#      sensitiveHeaders: Cookie,Set-Cookie
#      serviceId: auth-server
#      stripPrefix: true
#    department:
#      path: /department/**
#      sensitiveHeaders: Cookie,Set-Cookie,Authorization
#      serviceId: department-service
#      stripPrefix: false
#    employee:
#      path: /employee/**
#      sensitiveHeaders: Cookie,Set-Cookie,Authorization
#      serviceId: employee-service
#      stripPrefix: false
#    organization:
#      path: /organization/**
#      sensitiveHeaders: Cookie,Set-Cookie,Authorization
#      serviceId: organization-service
#      stripPrefix: false



ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
