server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  ignored-services: "*"

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
