server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  host:
    socket-timeout-millis: 60000
  add-host-header: true
  add-proxy-headers: true
  ignored-services: "*"

zuul:
  routes:
    auth:
      path: /uaa/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: auth-server
      stripPrefix: true
    department:
      path: /department/**
      serviceId: department-service
    employee:
      path: /employee/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: employee-service
      stripPrefix: false
    organization:
      path: /organization/**
      serviceId: organization-service

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
